# Generated by Django 3.2 on 2021-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionTeamDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=35)),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('present_address_street', models.CharField(max_length=15)),
                ('present_address_city', models.CharField(max_length=15)),
                ('present_address_zipCode', models.IntegerField()),
                ('present_address_state', models.CharField(max_length=15)),
                ('permanent_address_street', models.CharField(max_length=15)),
                ('permanent_address_city', models.CharField(max_length=15)),
                ('permanent_address_zipCode', models.IntegerField()),
                ('permanent_address_state', models.CharField(max_length=15)),
                ('mobile_number', models.IntegerField()),
                ('previous_employment', models.CharField(max_length=20)),
                ('yearsOfExperience', models.DecimalField(decimal_places=2, max_digits=2)),
                ('account_status', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
